In [113]:
# python notebook for Make Your Own Neural Network
# (c) Tariq Rashid, 2016
# license is GPLv2

In [114]:
import numpy
# scipy.special for the sigmoid function expit()
import scipy.special

# Calcular peso de los links del layer origen al destino


In [115]:
wa = [
        numpy.array(
        [[ 0.3, 0.3, 0.2 ],
         [ 0.2, 0.2, 0.1 ],
         [ 0.1, 0.5, 0.3 ]]),
        numpy.array(
        [[ 0.9, 0.6, 0.4 ],
         [ 0.2, 0.3, 0.2 ],
         [ 0.4, 0.1, 0.1 ]])
]

wb = [
    numpy.array(
        [[ 0.4, 0.2, 0.2 ],
         [ 0.2, 0.2, 0.8 ],
         [ 0.7, 0.5, 0.3 ]]),
    numpy.array(
        [[ 0.9, 0.6, 0.4 ],
         [ 0.2, 0.3, 0.2 ],
         [ 0.4, 0.1, 0.1 ]])
]

wc = [
    numpy.array(
        [[ 0.3, 0.3, 0.3 ],
         [ 0.1, 0.2, 0.1 ],
         [ 0.1, 0.5, 0.2 ]]),
    numpy.array(
        [[ 0.9, 0.6, 0.4 ],
         [ 0.2, 0.3, 0.2 ],
         [ 0.4, 0.1, 0.1 ]])
]

print (wa)

[array([[ 0.3,  0.3,  0.2],
       [ 0.2,  0.2,  0.1],
       [ 0.1,  0.5,  0.3]]), array([[ 0.9,  0.6,  0.4],
       [ 0.2,  0.3,  0.2],
       [ 0.4,  0.1,  0.1]])]


In [116]:
# neural network class definition
class neuralNetwork:
    
    
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate, weigths):
        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes

        self.wih = weigths[0] 
        self.who = weigths[1] 

        print("init wih")
        print(self.wih)
        
        print("init who")
        print(self.who)
        
        # learning rate
        self.lr = learningrate
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass

    
    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        
        print("Final ouput")
        print(final_outputs)
        
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        
        print("hidden_errors")
        print(hidden_errors)
        
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        
 
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        
        print("bp wih")
        print(self.wih)
        
        print("bp who")
        print(self.who)
        
        print("Output errors = target - final_outputs")
        print(output_errors)        
        
        pass

    
    # query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs

# Crear Neural Net

In [117]:
# number of input, hidden and output nodes
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

# learning rate is 0.3
learning_rate = 1

weigth = wa
# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate, weigth)

init wih
[[ 0.3  0.3  0.2]
 [ 0.2  0.2  0.1]
 [ 0.1  0.5  0.3]]
init who
[[ 0.9  0.6  0.4]
 [ 0.2  0.3  0.2]
 [ 0.4  0.1  0.1]]


In [118]:
n.train([0.1, 0.2, 0.3], [0.1, 0.2, 0.3])


Final ouput
[[ 0.73440954]
 [ 0.59247302]
 [ 0.57986125]]
hidden_errors
[[-0.76140769]
 [-0.52637376]
 [-0.36024455]]
bp wih
[[ 0.28107148  0.26214296  0.14321444]
 [ 0.18686727  0.17373454  0.0606018 ]
 [ 0.09108335  0.4821667   0.27325005]]
bp who
[[ 0.83349684  0.53534618  0.33196192]
 [ 0.14907201  0.25048823  0.14789657]
 [ 0.36335781  0.06437677  0.06251209]]
Output errors = target - final_outputs
[[-0.63440954]
 [-0.39247302]
 [-0.27986125]]


# 

# 